service: lambda-cert-updater
variablesResolutionMode: 20210326
frameworkVersion: '2'

provider:
  name: aws
  runtime: go1.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: ap-northeast-1
  deploymentBucket: serverless-upload-ap-northeast-1
  versionFunctions: false
  iam:
    role:
      statements:
        - Effect:   "Allow"
          Action:   ["s3:GetObject", "s3:PutObject"]
          Resource: { Fn::Join: ["", ["arn:aws:s3:::", { "Ref" : "CertificateBucket" }, "/*"]] }
        - Effect:   Allow
          Action:   ["route53:ListHostedZones", "route53:GetChange"]
          Resource: "*"
        - Effect:   Allow
          Action:   ["route53:ChangeResourceRecordSets"]
          Resource: "*"

functions:
  main:
    handler: handler
    description: cert updater
    timeout: 300
    memorySize: 1024
    environment:
      CERT_UPDATER_MAIL_ADDRESS: "${env:CERT_UPDATER_MAIL_ADDRESS}"
      CERT_UPDATER_OBTAIN_DOMAINS: "${env:CERT_UPDATER_OBTAIN_DOMAINS}"
      CERT_UPDATER_CERTIFICATE_BUCKET: "${env:CERT_UPDATER_CERTIFICATE_BUCKET}"
#    events:
#      - schedule: rate(10 minutes)

resources:
  Description: Fetch Let's Encrypt certificate
  Resources:
    CertificateBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: "${env:CERT_UPDATER_CERTIFICATE_BUCKET}"
